# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_ui.ui'
#
# Created: Tue Jun 23 11:01:44 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(704, 904)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tabData = QtGui.QTabWidget(self.centralwidget)
        self.tabData.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabData.setAutoFillBackground(True)
        self.tabData.setTabsClosable(True)
        self.tabData.setMovable(True)
        self.tabData.setObjectName(_fromUtf8("tabData"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(9, 9, 119, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btnSortPy = QtGui.QPushButton(self.tab_2)
        self.btnSortPy.setGeometry(QtCore.QRect(9, 28, 75, 23))
        self.btnSortPy.setObjectName(_fromUtf8("btnSortPy"))
        self.btnShowAllFiles = QtGui.QPushButton(self.tab_2)
        self.btnShowAllFiles.setGeometry(QtCore.QRect(9, 57, 75, 23))
        self.btnShowAllFiles.setObjectName(_fromUtf8("btnShowAllFiles"))
        self.txtYWGraph = QtGui.QListWidget(self.tab_2)
        self.txtYWGraph.setGeometry(QtCore.QRect(9, 86, 321, 190))
        self.txtYWGraph.setObjectName(_fromUtf8("txtYWGraph"))
        self.btnYWExtract = QtGui.QPushButton(self.tab_2)
        self.btnYWExtract.setGeometry(QtCore.QRect(9, 282, 75, 23))
        self.btnYWExtract.setObjectName(_fromUtf8("btnYWExtract"))
        self.btnModel = QtGui.QPushButton(self.tab_2)
        self.btnModel.setGeometry(QtCore.QRect(9, 311, 75, 23))
        self.btnModel.setObjectName(_fromUtf8("btnModel"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(9, 340, 63, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.txtErrorBox = QtGui.QTextBrowser(self.tab_2)
        self.txtErrorBox.setGeometry(QtCore.QRect(9, 359, 321, 191))
        self.txtErrorBox.setObjectName(_fromUtf8("txtErrorBox"))
        self.tabData.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.txtYWGraph_2 = QtGui.QListWidget(self.tab_4)
        self.txtYWGraph_2.setObjectName(_fromUtf8("txtYWGraph_2"))
        self.verticalLayout.addWidget(self.txtYWGraph_2)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.btnShowAllFiles_2 = QtGui.QPushButton(self.tab_4)
        self.btnShowAllFiles_2.setObjectName(_fromUtf8("btnShowAllFiles_2"))
        self.horizontalLayout_15.addWidget(self.btnShowAllFiles_2)
        spacerItem1 = QtGui.QSpacerItem(50, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.btnSortPy_2 = QtGui.QPushButton(self.tab_4)
        self.btnSortPy_2.setObjectName(_fromUtf8("btnSortPy_2"))
        self.horizontalLayout_15.addWidget(self.btnSortPy_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.boxView = QtGui.QGroupBox(self.tab_4)
        self.boxView.setObjectName(_fromUtf8("boxView"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.boxView)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btnProcessView = QtGui.QRadioButton(self.boxView)
        self.btnProcessView.setChecked(True)
        self.btnProcessView.setObjectName(_fromUtf8("btnProcessView"))
        self.horizontalLayout_14.addWidget(self.btnProcessView)
        self.btnDataView = QtGui.QRadioButton(self.boxView)
        self.btnDataView.setObjectName(_fromUtf8("btnDataView"))
        self.horizontalLayout_14.addWidget(self.btnDataView)
        self.btnCombinedView = QtGui.QRadioButton(self.boxView)
        self.btnCombinedView.setObjectName(_fromUtf8("btnCombinedView"))
        self.horizontalLayout_14.addWidget(self.btnCombinedView)
        self.horizontalLayout_10.addWidget(self.boxView)
        self.boxWorkflow = QtGui.QGroupBox(self.tab_4)
        self.boxWorkflow.setObjectName(_fromUtf8("boxWorkflow"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.boxWorkflow)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.chkWorkflowShow = QtGui.QCheckBox(self.boxWorkflow)
        self.chkWorkflowShow.setChecked(True)
        self.chkWorkflowShow.setObjectName(_fromUtf8("chkWorkflowShow"))
        self.horizontalLayout_8.addWidget(self.chkWorkflowShow)
        self.horizontalLayout_10.addWidget(self.boxWorkflow)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.boxLabel = QtGui.QGroupBox(self.tab_4)
        self.boxLabel.setObjectName(_fromUtf8("boxLabel"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.boxLabel)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkNameLabel = QtGui.QCheckBox(self.boxLabel)
        self.chkNameLabel.setChecked(True)
        self.chkNameLabel.setObjectName(_fromUtf8("chkNameLabel"))
        self.horizontalLayout_2.addWidget(self.chkNameLabel)
        self.chkURILabel = QtGui.QCheckBox(self.boxLabel)
        self.chkURILabel.setObjectName(_fromUtf8("chkURILabel"))
        self.horizontalLayout_2.addWidget(self.chkURILabel)
        self.horizontalLayout_5.addWidget(self.boxLabel)
        self.boxEdge = QtGui.QGroupBox(self.tab_4)
        self.boxEdge.setObjectName(_fromUtf8("boxEdge"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.boxEdge)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.chkLabelShow = QtGui.QCheckBox(self.boxEdge)
        self.chkLabelShow.setChecked(True)
        self.chkLabelShow.setObjectName(_fromUtf8("chkLabelShow"))
        self.horizontalLayout_7.addWidget(self.chkLabelShow)
        self.horizontalLayout_5.addWidget(self.boxEdge)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.boxLayout = QtGui.QGroupBox(self.tab_4)
        self.boxLayout.setObjectName(_fromUtf8("boxLayout"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.boxLayout)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.btnLRLayout = QtGui.QRadioButton(self.boxLayout)
        self.btnLRLayout.setChecked(True)
        self.btnLRLayout.setObjectName(_fromUtf8("btnLRLayout"))
        self.horizontalLayout_11.addWidget(self.btnLRLayout)
        self.btnRLLayout = QtGui.QRadioButton(self.boxLayout)
        self.btnRLLayout.setObjectName(_fromUtf8("btnRLLayout"))
        self.horizontalLayout_11.addWidget(self.btnRLLayout)
        self.btnTBLayout = QtGui.QRadioButton(self.boxLayout)
        self.btnTBLayout.setObjectName(_fromUtf8("btnTBLayout"))
        self.horizontalLayout_11.addWidget(self.btnTBLayout)
        self.btnBTLayout = QtGui.QRadioButton(self.boxLayout)
        self.btnBTLayout.setObjectName(_fromUtf8("btnBTLayout"))
        self.horizontalLayout_11.addWidget(self.btnBTLayout)
        self.verticalLayout.addWidget(self.boxLayout)
        self.boxPortLayout = QtGui.QGroupBox(self.tab_4)
        self.boxPortLayout.setObjectName(_fromUtf8("boxPortLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.boxPortLayout)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.btnPortGroup = QtGui.QRadioButton(self.boxPortLayout)
        self.btnPortGroup.setChecked(True)
        self.btnPortGroup.setObjectName(_fromUtf8("btnPortGroup"))
        self.horizontalLayout_13.addWidget(self.btnPortGroup)
        self.btnPortRelax = QtGui.QRadioButton(self.boxPortLayout)
        self.btnPortRelax.setObjectName(_fromUtf8("btnPortRelax"))
        self.horizontalLayout_13.addWidget(self.btnPortRelax)
        self.btnPortHide = QtGui.QRadioButton(self.boxPortLayout)
        self.btnPortHide.setObjectName(_fromUtf8("btnPortHide"))
        self.horizontalLayout_13.addWidget(self.btnPortHide)
        self.verticalLayout.addWidget(self.boxPortLayout)
        self.boxParameter = QtGui.QGroupBox(self.tab_4)
        self.boxParameter.setObjectName(_fromUtf8("boxParameter"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.boxParameter)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.btnParamShow = QtGui.QRadioButton(self.boxParameter)
        self.btnParamShow.setObjectName(_fromUtf8("btnParamShow"))
        self.horizontalLayout_12.addWidget(self.btnParamShow)
        self.btnParamReduce = QtGui.QRadioButton(self.boxParameter)
        self.btnParamReduce.setObjectName(_fromUtf8("btnParamReduce"))
        self.horizontalLayout_12.addWidget(self.btnParamReduce)
        self.btnParamHide = QtGui.QRadioButton(self.boxParameter)
        self.btnParamHide.setChecked(True)
        self.btnParamHide.setObjectName(_fromUtf8("btnParamHide"))
        self.horizontalLayout_12.addWidget(self.btnParamHide)
        self.verticalLayout.addWidget(self.boxParameter)
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnTopTitle = QtGui.QRadioButton(self.groupBox)
        self.btnTopTitle.setChecked(True)
        self.btnTopTitle.setObjectName(_fromUtf8("btnTopTitle"))
        self.horizontalLayout.addWidget(self.btnTopTitle)
        self.btnBottomTitle = QtGui.QRadioButton(self.groupBox)
        self.btnBottomTitle.setObjectName(_fromUtf8("btnBottomTitle"))
        self.horizontalLayout.addWidget(self.btnBottomTitle)
        self.btnHideTitle = QtGui.QRadioButton(self.groupBox)
        self.btnHideTitle.setObjectName(_fromUtf8("btnHideTitle"))
        self.horizontalLayout.addWidget(self.btnHideTitle)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnRename = QtGui.QCheckBox(self.groupBox_4)
        self.btnRename.setObjectName(_fromUtf8("btnRename"))
        self.horizontalLayout_3.addWidget(self.btnRename)
        self.txtRename = QtGui.QLineEdit(self.groupBox_4)
        self.txtRename.setObjectName(_fromUtf8("txtRename"))
        self.horizontalLayout_3.addWidget(self.txtRename)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnExport = QtGui.QCheckBox(self.groupBox_3)
        self.btnExport.setObjectName(_fromUtf8("btnExport"))
        self.horizontalLayout_6.addWidget(self.btnExport)
        self.txtExportDOT = QtGui.QLineEdit(self.groupBox_3)
        self.txtExportDOT.setObjectName(_fromUtf8("txtExportDOT"))
        self.horizontalLayout_6.addWidget(self.txtExportDOT)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.chkShowComments = QtGui.QCheckBox(self.groupBox_2)
        self.chkShowComments.setObjectName(_fromUtf8("chkShowComments"))
        self.horizontalLayout_4.addWidget(self.chkShowComments)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.btnYWGraph = QtGui.QPushButton(self.tab_4)
        self.btnYWGraph.setObjectName(_fromUtf8("btnYWGraph"))
        self.horizontalLayout_17.addWidget(self.btnYWGraph)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.WatchText = QtGui.QTextBrowser(self.tab_4)
        self.WatchText.setObjectName(_fromUtf8("WatchText"))
        self.verticalLayout_2.addWidget(self.WatchText)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.btnRunYW = QtGui.QPushButton(self.tab_4)
        self.btnRunYW.setObjectName(_fromUtf8("btnRunYW"))
        self.horizontalLayout_18.addWidget(self.btnRunYW)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.btnClearWatchText = QtGui.QPushButton(self.tab_4)
        self.btnClearWatchText.setObjectName(_fromUtf8("btnClearWatchText"))
        self.horizontalLayout_18.addWidget(self.btnClearWatchText)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        self.tabData.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.tabData)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuYW_Commands = QtGui.QMenu(self.menubar)
        self.menuYW_Commands.setObjectName(_fromUtf8("menuYW_Commands"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuYW_Commands.menuAction())

        self.retranslateUi(MainWindow)
        self.tabData.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", "Files in Current Directory", None))
        self.btnSortPy.setText(_translate("MainWindow", "Show .py files", None))
        self.btnShowAllFiles.setText(_translate("MainWindow", "Show all files", None))
        self.btnYWExtract.setText(_translate("MainWindow", "YW Extract", None))
        self.btnModel.setText(_translate("MainWindow", "YW Model", None))
        self.label.setText(_translate("MainWindow", "Message Box", None))
        self.tabData.setTabText(self.tabData.indexOf(self.tab_2), _translate("MainWindow", "YW Tools", None))
        self.label_5.setText(_translate("MainWindow", "Select a Python file to render:", None))
        self.btnShowAllFiles_2.setText(_translate("MainWindow", "Show all files", None))
        self.btnSortPy_2.setText(_translate("MainWindow", "Show .py files", None))
        self.boxView.setTitle(_translate("MainWindow", "Workflow View", None))
        self.btnProcessView.setText(_translate("MainWindow", "Process", None))
        self.btnDataView.setText(_translate("MainWindow", "Data", None))
        self.btnCombinedView.setText(_translate("MainWindow", "Combined", None))
        self.boxWorkflow.setTitle(_translate("MainWindow", "Workflow Box", None))
        self.chkWorkflowShow.setText(_translate("MainWindow", "Show", None))
        self.boxLabel.setTitle(_translate("MainWindow", "Data Label", None))
        self.chkNameLabel.setText(_translate("MainWindow", "Name", None))
        self.chkURILabel.setText(_translate("MainWindow", "URI", None))
        self.boxEdge.setTitle(_translate("MainWindow", "Edge Labels", None))
        self.chkLabelShow.setText(_translate("MainWindow", "Show", None))
        self.boxLayout.setTitle(_translate("MainWindow", "Layout", None))
        self.btnLRLayout.setText(_translate("MainWindow", "Left-Right", None))
        self.btnRLLayout.setText(_translate("MainWindow", "Right-Left", None))
        self.btnTBLayout.setText(_translate("MainWindow", "Top-Bottom", None))
        self.btnBTLayout.setText(_translate("MainWindow", "Bottom-Top", None))
        self.boxPortLayout.setTitle(_translate("MainWindow", "Port Layout", None))
        self.btnPortGroup.setText(_translate("MainWindow", "Group", None))
        self.btnPortRelax.setText(_translate("MainWindow", "Relax", None))
        self.btnPortHide.setText(_translate("MainWindow", "Hide", None))
        self.boxParameter.setTitle(_translate("MainWindow", "Parameters", None))
        self.btnParamShow.setText(_translate("MainWindow", "Show", None))
        self.btnParamReduce.setText(_translate("MainWindow", "Reduce", None))
        self.btnParamHide.setText(_translate("MainWindow", "Hide", None))
        self.groupBox.setTitle(_translate("MainWindow", "Graph Title Position", None))
        self.btnTopTitle.setText(_translate("MainWindow", "Top", None))
        self.btnBottomTitle.setText(_translate("MainWindow", "Bottom", None))
        self.btnHideTitle.setText(_translate("MainWindow", "Hide", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Graph Title Name", None))
        self.btnRename.setText(_translate("MainWindow", "Rename graph to:", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Export To .DOT File", None))
        self.btnExport.setText(_translate("MainWindow", "Export to", None))
        self.groupBox_2.setTitle(_translate("MainWindow", ".DOT Files Comments", None))
        self.chkShowComments.setText(_translate("MainWindow", "Show", None))
        self.btnYWGraph.setText(_translate("MainWindow", "YW Graph", None))
        self.label_3.setText(_translate("MainWindow", "Message Box", None))
        self.btnRunYW.setText(_translate("MainWindow", "Help", None))
        self.btnClearWatchText.setText(_translate("MainWindow", "Clear", None))
        self.tabData.setTabText(self.tabData.indexOf(self.tab_4), _translate("MainWindow", "Graph", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuYW_Commands.setTitle(_translate("MainWindow", "View", None))

